# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
# SPDX-FileCopyrightText:  2026 Timon Geiss
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "pypsa-earth-drc-myopic"
SPDX-PackageSupplier = "Timon Geiss, Anton Achhammer, Alexander Meisinger, Leon Schumm, Michael Sterner"
SPDX-PackageDownloadLocation = "https://github.com/timongeiss/pypsa-earth-drc-myopic"

[[annotations]]
path = "doc/data.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "doc/configtables/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "test/utils/agg_p_nom_minmax.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/agg_p_nom_minmax.csv"
precedence = "override"
SPDX-FileCopyrightText = [
  "The PyPSA-Earth and PyPSA-Eur Authors",
  "2026 Timon Geiss",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
  "data/custom/drc_myopic/demand_regions_*.csv",
  "data/custom/pipelines.csv",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Timon Geiss"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/custom/drc_myopic/base_network/*/custom_all_buses_build_network.csv"
precedence = "override"
SPDX-FileCopyrightText = [
  "OpenStreetMap contributors",
  "2026 Timon Geiss",
]
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = [
  "data/custom/drc_myopic/base_network/*/custom_all_converters_build_network.csv",
  "data/custom/drc_myopic/base_network/*/custom_all_transformers_build_network.csv",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Timon Geiss"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/custom/drc_myopic/base_network/*/custom_all_lines_build_network.csv"
precedence = "override"
SPDX-FileCopyrightText = [
  "OpenStreetMap contributors",
  "2026 Timon Geiss",
]
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = [
  "data/custom/export_ports.csv",
  "data/custom_powerplants.csv",
]
precedence = "override"
SPDX-FileCopyrightText = [
  "The PyPSA-Earth and PyPSA-Eur Authors",
  "2026 Timon Geiss",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC0-1.0"
