# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "pypsa-earth-drc-myopic"
SPDX-PackageSupplier = "Timon Geiss, Anton Achhammer, Alexander Meisinger, Leon Schumm, Michael Sterner"
SPDX-PackageDownloadLocation = "https://github.com/timongeiss/pypsa-earth-drc-myopic"

[[annotations]]
path = "doc/data.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "doc/configtables/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "test/utils/agg_p_nom_minmax.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/agg_p_nom_minmax.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
  "data/custom/drc_myopic/**",
  "data/custom/export_ports.csv",
  "data/custom/pipelines.csv",
  "data/custom_powerplants.csv",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Timon Geiss, Anton Achhammer, Alexander Meisinger, Leon Schumm, Michael Sterner"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The PyPSA-Earth and PyPSA-Eur Authors"
SPDX-License-Identifier = "CC0-1.0"
